apiVersion: v1
kind: Pod
metadata:
  name: shared-gpu-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]

      resources:
        limits:
          deepomatic.com/shared-gpu: 1 # requesting 1 shared GPU
